#requires -Version 5.1
[CmdletBinding()]
param(
  [string]$ProjectPath = 'C:\Users\hramirez\Documents\PROYECTOS-H\ZelogiG',
  [switch]$Commit,
  [switch]$Push
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Encoded([string]$RelativePath, [string]$Payload) {
  $target = Join-Path $ProjectPath $RelativePath
  $parent = Split-Path -Parent $target
  if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
  if (Test-Path -LiteralPath $target) {
    $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    Copy-Item -LiteralPath $target -Destination "$target.backup-$stamp" -Force
  }
  [IO.File]::WriteAllBytes($target, [Convert]::FromBase64String($Payload))
  Write-Host "ACTUALIZADO: $RelativePath" -ForegroundColor Green
}

Write-Host 'ZelogiG - Elevación técnica y creativa' -ForegroundColor Cyan
Write-Host 'Se registrará la tarea en la bitácora.' -ForegroundColor Yellow

Write-Encoded 'docs\26_engine_architecture.md' 'IyBBcnF1aXRlY3R1cmEgZGVsIG1vdG9yCgojIyBEZWNpc2nDs24gcHJvcHVlc3RhCgpaZWxvZ2lHIHV0aWxpemFyw6EgdW4gbsO6Y2xlbyBmdW5jaW9uYWwgeSBkZXRlcm1pbmlzdGEuIEVsIGVzdGFkbyBkZWwgdGFibGVybyBlbnRyYSBhIHVuYSBmdW5jacOzbiBqdW50byBjb24gdW5hIGludGVuY2nDs24gZGVsIGp1Z2Fkb3IsIHkgbGEgZnVuY2nDs24gZGV2dWVsdmUgdW4gZXN0YWRvIG51ZXZvIHNpbiBtdXRhciBlbCBhbnRlcmlvci4KCiMjIEZsdWpvCgpgYGB0ZXh0CkdhbWVTdGF0ZSArIFBsYXllckludGVudCAtPiBWYWxpZGF0ZSAtPiBNb3ZlL1B1c2ggLT4gUGFyc2VSdWxlcyAtPiBBcHBseUVmZmVjdHMgLT4gRXZhbHVhdGVWaWN0b3J5IC0+IEdhbWVTdGF0ZQpgYGAKCiMjIENhcGFzCgotICoqRG9taW5pbzoqKiB0aXBvcywgbW92aW1pZW50bywgZW1wdWplLCByZWdsYXMsIGVmZWN0b3MsIHZpY3RvcmlhIGUgaGlzdG9yaWFsLiBObyBjb25vY2UgUmVhY3QsIG5hdmVnYWRvciwgVGFpbHdpbmQsIFN1cGFiYXNlIG5pIGFyY2hpdm9zLgotICoqQXBsaWNhY2nDs246KiogY29vcmRpbmEgYWNjaW9uZXMgY29tbyBpbmljaWFyIHBhcnRpZGEsIG1vdmVyLCBkZXNoYWNlciwgcmVpbmljaWFyIHkgY29tcGxldGFyIG5pdmVsLgotICoqSW50ZXJmYXo6KiogcmVwcmVzZW50YSBlbCBlc3RhZG8sIGNhcHR1cmEgdGVjbGFkbywgdGFjdG8geSBjb250cm9sZXMgYWNjZXNpYmxlcy4KLSAqKkluZnJhZXN0cnVjdHVyYToqKiBwcm9ncmVzbyBsb2NhbCwgU3VwYWJhc2UsIGF1ZGlvLCB2aWJyYWNpw7NuIHkgdGVsZW1ldHLDrWEgZnV0dXJhLgoKIyMgT3JpZW50YWNpw7NuIGEgb2JqZXRvcyB5IFNPTElECgpObyBzZSB1dGlsaXphcsOhbiBjbGFzZXMgcG9yIGRlZmVjdG8uIExvcyBtb2RlbG9zIGRlbCBqdWVnbyBzZXLDoW4gZGF0b3MgaW5tdXRhYmxlcyB5IGZ1bmNpb25lcyBwdXJhcy4gTGEgb3JpZW50YWNpw7NuIGEgb2JqZXRvcyBzZSByZXNlcnZhcsOhIHBhcmEgYWRhcHRhZG9yZXMgY29uIGNpY2xvIGRlIHZpZGEgcmVhbCBvIGludGVncmFjacOzbiBleHRlcm5hLgoKU09MSUQgc2UgYXBsaWNhcsOhIGNvbW8gY3JpdGVyaW8gZGUgZGlzZcOxbywgbm8gY29tbyBjZXJlbW9uaWE6CgoxLiBVbiBtw7NkdWxvIHRpZW5lIHVuYSByZXNwb25zYWJpbGlkYWQgcmVjb25vY2libGUuCjIuIE51ZXZhcyBwcm9waWVkYWRlcyBkZWwganVlZ28gc2UgYWdyZWdhbiBzaW4gcmVlc2NyaWJpciBlbCBtb3RvciBjb21wbGV0by4KMy4gSW1wbGVtZW50YWNpb25lcyBsb2NhbGVzIHkgcmVtb3RhcyByZXNwZXRhbiBsb3MgbWlzbW9zIGNvbnRyYXRvcy4KNC4gTG9zIGNvbnRyYXRvcyBzb24gcGVxdWXDsW9zLgo1LiBFbCBkb21pbmlvIGRlcGVuZGUgZGUgYWJzdHJhY2Npb25lcywgbnVuY2EgZGUgcHJvdmVlZG9yZXMuCgojIyBMw61taXRlcyBkZSB0YW1hw7FvCgotIERpdmlkaXIgcG9yIHJlc3BvbnNhYmlsaWRhZCwgbm8gcG9yIG7Dum1lcm8gYXJiaXRyYXJpbyBkZSBsw61uZWFzLgotIEV2aXRhciBhcmNoaXZvcyBxdWUgbWV6Y2xlbiBjw6FsY3VsbywgaW50ZXJmYXogeSBwZXJzaXN0ZW5jaWEuCi0gQW50ZXMgZGUgZXh0cmFlciB1bmEgYWJzdHJhY2Npw7NuLCBkZWJlbiBleGlzdGlyIGFsIG1lbm9zIGRvcyB1c29zIHJlYWxlcyBvIHVuYSBmcm9udGVyYSBhcnF1aXRlY3TDs25pY2EgY2xhcmEuCg=='
Write-Encoded 'docs\27_art_direction.md' 'IyBEaXJlY2Npw7NuIGFydMOtc3RpY2EKCiMjIElkZW50aWRhZAoKWmVsb2dpRyBlcyB1biB2aWRlb2p1ZWdvIDJEIGRlIHJvbXBlY2FiZXphcyBsaW5nw7zDrXN0aWNvcyBkb25kZSBsYXMgcGFsYWJyYXMgcmVlc2NyaWJlbiBlbCBtdW5kby4KCiMjIEVzdGlsbwoKU29mdC1UZWNoIGzDumRpY286IGZvcm1hcyByZWRvbmRlYWRhcywgbWF0ZXJpYWxlcyBzdWF2ZXMsIGNvbnRyYXN0ZSBjbGFybyB5IHVuIG11bmRvIHF1ZSBwYXJlY2UgY29uc3RydWlkbyBjb24gcGllemFzIHTDoWN0aWxlcy4KCiMjIFNpc3RlbWEgdmlzdWFsIGluaWNpYWwKCi0gQXJ0ZSBiYXNlOiBDU1MgeSBTVkcuCi0gUGVyc3BlY3RpdmE6IGZyb250YWwgbyBsaWdlcmFtZW50ZSBlbGV2YWRhLCBzaW4gcHJvZnVuZGlkYWQgZmFsc2EgcXVlIGRpZmljdWx0ZSBsZWVyIGxhIGN1YWRyw61jdWxhLgotIFBhbGV0YTogbGF2YW5kYSwgcm9zYSBzdWF2ZSwgbWVudGEsIGF6dWwgY2xhcm8geSBuZXV0cm9zIGPDoWxpZG9zLgotIENvbnRvcm5vczogY29uc3RhbnRlcyB5IHN1ZmljaWVudGVtZW50ZSB2aXNpYmxlcy4KLSBTb21icmFzOiBjb3J0YXMgeSBzdWF2ZXM7IG51bmNhIGRlYmVuIG9jdWx0YXIgbMOtbWl0ZXMgZGUgY2VsZGEuCi0gVGV4dG86IGxlZ2libGUgZW4gcGFudGFsbGFzIHBlcXVlw7FhcyB5IGRpc3Rpbmd1aWJsZSBkZWwgZGVjb3JhZG8uCi0gTW92aW1pZW50bzogYnJldmUsIGNvbXVuaWNhdGl2byB5IHJlc3BldHVvc28gZGUgYHByZWZlcnMtcmVkdWNlZC1tb3Rpb25gLgoKIyMgUmVnbGFzIGRlIGJsb3F1ZXMKCi0gTG9zIGJsb3F1ZXMgZGUgcGFsYWJyYXMgc2llbXByZSBtdWVzdHJhbiB0ZXh0by4KLSBTdXN0YW50aXZvLCBvcGVyYWRvciB5IHByb3BpZWRhZCBzZSBkaXN0aW5ndWVuIHBvciBtw6FzIGRlIHVuIGNhbmFsOiBjb2xvciwgcGF0csOzbiwgZm9ybWEgbyBzw61tYm9sby4KLSBMb3Mgb2JqZXRvcyBjb21wYXJ0ZW4gbGVuZ3VhamUgdmlzdWFsIGNvbiBzdSBwYWxhYnJhLCBzaW4gY29uZnVuZGlyc2UgY29uIGVsbGEuCi0gTmluZ8O6biByZWN1cnNvIHZpc3VhbCBwdWVkZSBhbHRlcmFyIGVsIHRhbWHDsW8gbMOzZ2ljbyBkZSBsYSBjZWxkYS4KCiMjIFByb2hpYmlkbwoKLSBDb3BpYXIgaWRlbnRpZGFkLCBwZXJzb25hamVzLCBuaXZlbGVzIG8gcmVjdXJzb3MgZGUgb3Ryb3MganVlZ29zLgotIE1lemNsYXIgZXN0aWxvcyBnZW5lcmFkb3Mgc2luIG5vcm1hbGl6YWNpw7NuLgotIFVzYXIgaW3DoWdlbmVzIGNvbiB0ZXh0byBnZW5lcmFkbyBwb3IgSUEuCi0gRGVwZW5kZXIgc29sbyBkZWwgY29sb3IuCi0gQWdyZWdhciBkZWNvcmFjacOzbiBxdWUgcmVkdXpjYSBsYSBsZWN0dXJhIGRlbCBwdXp6bGUuCg=='
Write-Encoded 'docs\28_ai_asset_workflow.md' 'IyBGbHVqbyBkZSByZWN1cnNvcyB2aXN1YWxlcyBhc2lzdGlkb3MgcG9yIElBCgojIyBQcmluY2lwaW8KCkxhIElBIGdlbmVyYSBjb25jZXB0b3MsIG5vIGRlY2lkZSBsYSBpZGVudGlkYWQgZmluYWwuIFRvZG8gcmVjdXJzbyBwYXNhIHBvciBzZWxlY2Npw7NuIGh1bWFuYSwgbm9ybWFsaXphY2nDs24geSByZWdpc3RybyBkZSBwcm9jZWRlbmNpYS4KCiMjIEZsdWpvCgoxLiBEZWZpbmlyIGxhIG5lY2VzaWRhZCBkZWwgbml2ZWwuCjIuIENvbnN1bHRhciBsYSBkaXJlY2Npw7NuIGFydMOtc3RpY2EuCjMuIENyZWFyIHVuIHByb21wdCBzaW4gbWFyY2FzLCBwZXJzb25hamVzIG8gZXN0aWxvcyBwcm90ZWdpZG9zLgo0LiBHZW5lcmFyIGNvbmNlcHRvcyBjb24gdW5hIGhlcnJhbWllbnRhIGF1dG9yaXphZGEuCjUuIFNlbGVjY2lvbmFyIHVuYSBwcm9wdWVzdGEuCjYuIFJlZGlidWphciBvIG5vcm1hbGl6YXIgY29tbyBTVkcgbyBzcHJpdGUgY29uc2lzdGVudGUuCjcuIFByb2JhciBsZWdpYmlsaWRhZCBlbiBsYSBjdWFkcsOtY3VsYSB5IGVuIG3Ds3ZpbC4KOC4gT3B0aW1pemFyIHRhbWHDsW8uCjkuIFJlZ2lzdHJhciBoZXJyYW1pZW50YSwgZmVjaGEsIHByb21wdCwgbW9kaWZpY2FjaW9uZXMgeSBsaWNlbmNpYS4KMTAuIEFwcm9iYXIgYW50ZXMgZGUgaW5jb3Jwb3JhciBhbCBqdWVnby4KCiMjIFJlZ2lzdHJvIG3DrW5pbW8gcG9yIHJlY3Vyc28KCi0gSWRlbnRpZmljYWRvciB5IHJ1dGEuCi0gRnVuY2nDs24gZGVudHJvIGRlbCBqdWVnby4KLSBBdXRvciBodW1hbm8gcmVzcG9uc2FibGUuCi0gSGVycmFtaWVudGEgbyBmdWVudGUuCi0gRmVjaGEuCi0gUHJvbXB0LCBzaSBhcGxpY2EuCi0gVHJhbnNmb3JtYWNpb25lcyByZWFsaXphZGFzLgotIENvbmRpY2lvbmVzIGRlIHVzbyBjb25vY2lkYXMuCi0gRXN0YWRvOiBjb25jZXB0bywgYXByb2JhZG8gbyByZXRpcmFkby4KCiMjIFJlZ2xhIGRlIHNlZ3VyaWRhZAoKTm8gY2FyZ2FyIHNlY3JldG9zLCBkYXRvcyBwZXJzb25hbGVzLCBhcmNoaXZvcyBpbnRlcm5vcyBuaSBtYXRlcmlhbCBkZSB0ZXJjZXJvcyBzaW4gcGVybWlzbyBhIHVuYSBoZXJyYW1pZW50YSBkZSBJQS4K'
Write-Encoded 'docs\29_development_environment.md' 'IyBFbnRvcm5vIGRlIGRlc2Fycm9sbG8KCiMjIE9iamV0aXZvCgpVbiBjaWNsbyBjb3J0bzogZWRpdGFyLCBndWFyZGFyLCB2ZXIgZW4gbG9jYWxob3N0LCBlamVjdXRhciB1bmEgcHJ1ZWJhIGNvbmNyZXRhIHkgcmVnaXN0cmFyIGVsIHJlc3VsdGFkby4KCiMjIEJhc2UKCi0gV2luZG93cy4KLSBWaXN1YWwgU3R1ZGlvIENvZGUuCi0gR2l0LgotIE5vZGUuanMgTFRTLgotIE5QTSBpbmNsdWlkbyBjb24gTm9kZS5qcy4KLSBOYXZlZ2Fkb3IgQ2hyb21pdW0geSwgY3VhbmRvIHNlYSBwb3NpYmxlLCBGaXJlZm94LgoKIyMgQ29tYW5kb3Mgb2JqZXRpdm8KCmBgYHBvd2Vyc2hlbGwKbnBtIHJ1biBkZXYKbnBtIHJ1biB0eXBlY2hlY2sKbnBtIHJ1biBsaW50Cm5wbSBydW4gdGVzdApucG0gcnVuIHRlc3Q6d2F0Y2gKbnBtIHJ1biB0ZXN0OmUyZQpucG0gcnVuIGJ1aWxkCmBgYAoKIyMgRW50b3Jub3MKCi0gKipMb2NhbDoqKiBtb3RvciB5IGNpbmNvIG5pdmVsZXMgc2luIHNlcnZpY2lvcyBleHRlcm5vcy4KLSAqKlByZXZpZXc6KiogZGVzcGxpZWd1ZSB0ZW1wb3JhbCBwYXJhIHByb2JhciBpbnRlcmZheiB5IG3Ds3ZpbC4KLSAqKlByb2R1Y2Npw7NuOioqIHZlcnNpw7NuIGFwcm9iYWRhIHkgZXN0YWJsZS4KCiMjIExhYm9yYXRvcmlvCgpgc3JjL2FwcC9sYWIvYCBzZXJ2aXLDoSBwYXJhIHByb2JhciB0YWJsZXJvLCByZWdsYXMsIGFuaW1hY2lvbmVzLCB0YWN0byB5IGFjY2VzaWJpbGlkYWQuIE5vIGVzIHVuYSBydXRhIHDDumJsaWNhIGRlIHByb2R1Y2Npw7NuIHkgbm8gc2UgY29udmllcnRlIGVuIHVuYSBzZWd1bmRhIGFycXVpdGVjdHVyYS4KCiMjIENvbmRpY2lvbmVzIHBhcmEgY29uZWN0YXIgU3VwYWJhc2UKCjEuIEVsIG5pdmVsIGxvY2FsIGZ1bmNpb25hLgoyLiBMYXMgcHJ1ZWJhcyBkZWwgbW90b3IgcGFzYW4uCjMuIEV4aXN0ZSB1bmEgbmVjZXNpZGFkIGRlIGlkZW50aWRhZCBvIHNpbmNyb25pemFjacOzbi4KNC4gRWwgbW9kZWxvIGRlIGRhdG9zIGVzdMOhIGFwcm9iYWRvLgo1LiBMYXMgdmFyaWFibGVzIGRlIGVudG9ybm8gZXN0w6FuIGRvY3VtZW50YWRhcyB5IGxvcyBzZWNyZXRvcyBubyBsbGVnYW4gYWwgY2xpZW50ZS4K'
Write-Encoded 'docs\30_level_creation_pipeline.md' 'IyBQcm9jZXNvIGRlIGNyZWFjacOzbiBkZSBuaXZlbGVzCgojIyBFdGFwYXMKCjEuIERlZmluaXIgbGEgaWRlYSBsaW5nw7zDrXN0aWNhIHkgbGEgZW1vY2nDs24gZGVsIG5pdmVsLgoyLiBFc2NyaWJpciBsYSByZWdsYSBudWV2YSBxdWUgc2UgZW5zZcOxYS4KMy4gRGlzZcOxYXIgdW5hIHNvbHVjacOzbiBwcmluY2lwYWwgeSBhbCBtZW5vcyB1biBpbnRlbnRvIHJhem9uYWJsZSBxdWUgZmFsbGUgZGUgZm9ybWEgY29tcHJlbnNpYmxlLgo0LiBDcmVhciBlbCBuaXZlbCBlbiBlbCBmb3JtYXRvIHZlcnNpb25hZG8uCjUuIFZhbGlkYXIgZGltZW5zaW9uZXMsIGlkZW50aWZpY2Fkb3JlcyB5IHBvc2ljaW9uZXMuCjYuIFByb2JhciBtYW51YWxtZW50ZSBjb24gdGVjbGFkbyB5IHRhY3RvLgo3LiBSZWdpc3RyYXIgdW5hIHNvbHVjacOzbiBjb25vY2lkYS4KOC4gRWplY3V0YXIgcHJ1ZWJhcyBkZSByZWdyZXNpw7NuLgo5LiBQcm9iYXIgY29uIHVuYSBwZXJzb25hIHF1ZSBubyBjb25vemNhIGxhIHNvbHVjacOzbi4KMTAuIFB1YmxpY2FyIHNvbG8gY3VhbmRvIGVsIGFwcmVuZGl6YWplIHkgbGEgZGl2ZXJzacOzbiBzZWFuIGNsYXJvcy4KCiMjIFJlZ2xhIGRlIHByb2dyZXNpw7NuCgpDYWRhIG5pdmVsIHByZXNlbnRhIHVuYSBpZGVhIGRvbWluYW50ZS4gUHVlZGUgcmV1dGlsaXphciByZWdsYXMgYW50ZXJpb3JlcywgcGVybyBubyBkZWJlIGludHJvZHVjaXIgdmFyaWFzIGV4Y2VwY2lvbmVzIG51ZXZhcyBhIGxhIHZlei4KCiMjIEVkaXRvciBkZSBuaXZlbGVzCgpObyBzZSBjb25zdHJ1aXLDoSBoYXN0YSBjb21wbGV0YXIgY2luY28gbml2ZWxlcyBtYW51YWxlcyB5IGRvY3VtZW50YXIgcXXDqSB0YXJlYXMgc2UgcmVwaXRlbi4gTGEgaGVycmFtaWVudGEgbmFjZXLDoSBkZSBldmlkZW5jaWEsIG5vIGRlIGltYWdpbmFjacOzbi4K'
Write-Encoded 'docs\31_quality_gates.md' 'IyBQdWVydGFzIGRlIGNhbGlkYWQKCiMjIEFudGVzIGRlIGFjZXB0YXIgY8OzZGlnbwoKLSBBcnF1aXRlY3R1cmEgcmV2aXNhZGEuCi0gRGVjaXNpw7NuIGFwcm9iYWRhIHNpIGNhbWJpYSBkZXBlbmRlbmNpYXMsIGRhdG9zIG8gY29tcG9ydGFtaWVudG8gY2VudHJhbC4KLSBUaXBvcyBlc3RyaWN0b3Mgc2luIGVzY2FwZXMgaW5uZWNlc2FyaW9zLgotIERvbWluaW8gc2VwYXJhZG8gZGUgaW50ZXJmYXogZSBpbmZyYWVzdHJ1Y3R1cmEuCi0gUHJ1ZWJhcyBudWV2YXMgbyBhY3R1YWxpemFkYXMuCi0gQWNjZXNpYmlsaWRhZCByZXZpc2FkYS4KLSBEb2N1bWVudGFjacOzbiB5IGRpYWdyYW1hIGFmZWN0YWRvcyBhY3R1YWxpemFkb3MuCi0gQml0w6Fjb3JhIGFjdHVhbGl6YWRhLgoKIyMgQW50ZXMgZGUgaW50ZWdyYXIgdW4gbml2ZWwKCi0gRG9jdW1lbnRvIHbDoWxpZG8uCi0gU29sdWNpw7NuIG1hbnVhbCByZWdpc3RyYWRhLgotIFNpbiBpZGVudGlmaWNhZG9yZXMgZHVwbGljYWRvcy4KLSBTaW4gcG9zaWNpb25lcyBmdWVyYSBkZWwgdGFibGVyby4KLSBQcm9iYWRvIGNvbiB0ZWNsYWRvIHkgdGFjdG8uCi0gVGV4dG8gbGVnaWJsZSBlbiBtw7N2aWwuCi0gUmVnbGEgZWR1Y2F0aXZhIGNvbXByZW5zaWJsZS4KCiMjIEFudGVzIGRlIHB1YmxpY2FyCgpgYGBwb3dlcnNoZWxsCm5wbSBydW4gdHlwZWNoZWNrCm5wbSBydW4gbGludApucG0gcnVuIHRlc3QKbnBtIHJ1biB0ZXN0OmUyZQpucG0gcnVuIGJ1aWxkCmBgYAoKTnVuY2Egc2UgZGViaWxpdGEgdW5hIHZhbGlkYWNpw7NuIHBhcmEgb2J0ZW5lciB1bmEgc2FsaWRhIHZlcmRlLiBTZSBjb3JyaWdlIGxhIGNhdXNhIG8gc2UgcmVnaXN0cmEgZWwgYmxvcXVlby4K'
Write-Encoded 'docs\32_decision_backlog.md' 'IyBEZWNpc2lvbmVzIHBlbmRpZW50ZXMKCkxhcyBzaWd1aWVudGVzIGRlY2lzaW9uZXMgbm8gYXV0b3JpemFuIGNhbWJpb3MuIERlYmVuIHByZXNlbnRhcnNlIGFsIHByb3BpZXRhcmlvIGNvbiBvcGNpb25lcywgY29zdG8sIHJpZXNnbywgaW1wYWN0byB5IHJldmVyc2liaWxpZGFkLgoKIyMgRC0wMDEgR2VzdGnDs24gZGUgZXN0YWRvCgotIEVzdGFkbzogcGVuZGllbnRlIGRlIGV2aWRlbmNpYS4KLSBCYXNlIGFjdHVhbDogcmVkdWNlciBvIGNvbnRyb2xhZG9yIFJlYWN0IHNvYnJlIGRvbWluaW8gcHVyby4KLSBBbHRlcm5hdGl2YSBmdXR1cmE6IFp1c3RhbmQuCi0gRGlzcGFyYWRvcjogbcO6bHRpcGxlcyBjb25zdW1pZG9yZXMgaW5kZXBlbmRpZW50ZXMsIHBlcnNpc3RlbmNpYSBjb21wbGVqYSBvIHNpbmNyb25pemFjacOzbi4KCiMjIEQtMDAyIFJlY3Vyc29zIHZpc3VhbGVzIGZpbmFsZXMKCi0gRXN0YWRvOiBDU1MgeSBTVkcgYXByb2JhZG9zIHBhcmEgTVZQLgotIFBlbmRpZW50ZTogaGVycmFtaWVudGEgZGUgSUEgcGFyYSBjb25jZXB0b3MgeSBjb25kaWNpb25lcyBkZSB1c28gY29tZXJjaWFsLgoKIyMgRC0wMDMgU29uaWRvIHkgbcO6c2ljYQoKLSBFc3RhZG86IHBlbmRpZW50ZS4KLSBQcmVndW50YXM6IGlkZW50aWRhZCBzb25vcmEsIGFjY2VzaWJpbGlkYWQsIGxpY2VuY2lhcyB5IGNvbnRyb2wgZGUgdm9sdW1lbi4KCiMjIEQtMDA0IEVkaXRvciBkZSBuaXZlbGVzCgotIEVzdGFkbzogcG9zcHVlc3RvIGhhc3RhIGNvbXBsZXRhciBjaW5jbyBuaXZlbGVzIG1hbnVhbGVzLgoKIyMgRC0wMDUgU3VwYWJhc2UKCi0gRXN0YWRvOiBwb3NwdWVzdG8gaGFzdGEgdmFsaWRhciBlbCBqdWVnbyBsb2NhbC4KCiMjIEQtMDA2IE1vbmV0aXphY2nDs24KCi0gRXN0YWRvOiBleHBsb3JhY2nDs24uCi0gQWx0ZXJuYXRpdmFzOiBkZW1vIG3DoXMgY29tcHJhIMO6bmljYSwgZXhwYW5zaW9uZXMsIGVkaWNpw7NuIGVkdWNhdGl2YS4KLSBQcm9oaWJpZG8gZGlzZcOxYXIgbW9uZXRpemFjacOzbiBxdWUgZGV0ZXJpb3JlIGVsIHB1enpsZSBvIGV4cGxvdGUgZnJ1c3RyYWNpw7NuLgoKIyMgRC0wMDcgR3JhcGhpZnkKCi0gRXN0YWRvOiBwZW5kaWVudGUuCi0gUmVxdWllcmUgZXZhbHVhY2nDs24gZGUgcHJpdmFjaWRhZCwgY29zdG8gb3BlcmF0aXZvIHkgdXRpbGlkYWQgcmVhbC4KCiMjIEQtMDA4IEZsdWpvIEdpdAoKLSBFc3RhZG86IHJlcG9zaXRvcmlvIGluaWNpYWwgZW4gYG1haW5gLgotIFBlbmRpZW50ZTogZGVjaWRpciBlbnRyZSBmbHVqbyBzaW1wbGUgcG9yIHJhbWFzIGNvcnRhcyBvIGBtYWluL3FhL2RldmAgY3VhbmRvIGV4aXN0YSB1biBjaWNsbyByZWFsIGRlIHBydWViYXMgeSBwdWJsaWNhY2nDs24uCg=='
Write-Encoded 'docs\33_ai_handoff.md' 'IyBFbnRyZWdhIGRlIGNvbnRleHRvIGEgb3RyYSBJQQoKIyMgUGFxdWV0ZSBtw61uaW1vCgoxLiBgQ0xBVURFLm1kYC4KMi4gYFBST0pFQ1RfR0VORVNJUy5tZGAuCjMuIGBkb2NzL1NUQVRVUy5tZGAuCjQuIExhcyB0cmVzIGVudHJhZGFzIG3DoXMgcmVjaWVudGVzIGRlIGBkb2NzL2JpdGFjb3JhLm1kYC4KNS4gRWwgZG9jdW1lbnRvIGRlIGRlY2lzacOzbiByZWxhY2lvbmFkby4KNi4gU29sbyBsb3MgYXJjaGl2b3MgZGUgY8OzZGlnbyBhZmVjdGFkb3MuCgojIyBQcm9tcHQgYmFzZQoKYGBgdGV4dApUcmFiYWphIGVuIFplbG9naUcuIEFudGVzIGRlIG1vZGlmaWNhciwgbGVlIENMQVVERS5tZCwgUFJPSkVDVF9HRU5FU0lTLm1kLCBkb2NzL1NUQVRVUy5tZCB5IGxhcyB0cmVzIGVudHJhZGFzIHJlY2llbnRlcyBkZSBkb2NzL2JpdGFjb3JhLm1kLgoKVGFyZWE6IFtkZXNjcmliaXIgdW4gcmVzdWx0YWRvIHBlcXVlw7FvIHkgdmVyaWZpY2FibGVdLgoKUHJpbWVybyBwcmVzZW50YSBsYSBkZWNpc2nDs24gdMOpY25pY2EsIGFsdGVybmF0aXZhcywgY29zdG8sIHJpZXNnb3MsIGltcGFjdG8geSByZXZlcnNpYmlsaWRhZC4gTm8gbW9kaWZpcXVlcyBhcnF1aXRlY3R1cmEgbyBjw7NkaWdvIGhhc3RhIHJlY2liaXIgYXByb2JhY2nDs24gY3VhbmRvIGxhIHRhcmVhIGNhbWJpZSBkZXBlbmRlbmNpYXMsIGRhdG9zLCBjb250cmF0b3MgZGVsIG1vdG9yIG8gZXhwZXJpZW5jaWEgY2VudHJhbC4KCk5vIGludmVudGVzIHBydWViYXMuIE5vIGFncmVndWVzIGRlcGVuZGVuY2lhcyBwb3IgY29tb2RpZGFkLiBNYW50w6luIGVsIGRvbWluaW8gaW5kZXBlbmRpZW50ZSBkZSBSZWFjdCB5IFN1cGFiYXNlLiBBbCBjZXJyYXIsIGFjdHVhbGl6YSBkb2N1bWVudGFjacOzbiwgZGlhZ3JhbWFzIHkgYml0w6Fjb3JhLgpgYGAKCiMjIFNpIGxhIElBIG5vIHB1ZWRlIGVkaXRhciBhcmNoaXZvcwoKRGViZSBlbnRyZWdhcjoKCi0gUnV0YSBleGFjdGEuCi0gQ29udGVuaWRvIGNvbXBsZXRvIG8gcGFyY2hlIGNsYXJvLgotIENvbWFuZG9zIGRlIHZhbGlkYWNpw7NuLgotIFJlc3VsdGFkbyBlc3BlcmFkby4KLSBFbnRyYWRhIGRlIGJpdMOhY29yYSBwcmVwYXJhZGEuCg=='
Write-Encoded 'docs\34_product_identity.md' 'IyBJZGVudGlkYWQgZGVsIHByb2R1Y3RvCgojIyBEZWZpbmljacOzbiBvZmljaWFsCgpaZWxvZ2lHIGVzIHVuIHZpZGVvanVlZ28gMkQgZGUgcm9tcGVjYWJlemFzIGxpbmfDvMOtc3RpY29zIGRvbmRlIGxhcyBwYWxhYnJhcyByZWVzY3JpYmVuIGVsIG11bmRvLgoKIyMgUXXDqSBlcwoKLSBVbiBqdWVnbyBkZSBsw7NnaWNhLgotIFVuYSBleHBlcmllbmNpYSB2aXN1YWwgeSB0w6FjdGlsLgotIFVuIHNpc3RlbWEgZGUgcmVnbGFzIGNvbWJpbmFibGVzLgotIFVuYSBmb3JtYSBkZSBkZXNjdWJyaXIgZXN0cnVjdHVyYXMgZGVsIGluZ2zDqXMgbWVkaWFudGUgY29uc2VjdWVuY2lhcy4KCiMjIFF1w6kgbm8gZXMKCi0gVW4gc2ltdWxhZG9yIHByb2Zlc2lvbmFsLgotIFVuIGN1cnNvIHRyYWRpY2lvbmFsLgotIFVuYSBsaXN0YSBkZSBlamVyY2ljaW9zLgotIFVuYSBwbGF0YWZvcm1hIGVtcHJlc2FyaWFsLgotIFVuYSBjb3BpYSB2aXN1YWwgbyBtZWPDoW5pY2EgZGUgdW5hIG9icmEgZXhpc3RlbnRlLgoKIyMgUHJvbWVzYQoKTW92ZXIgcGFsYWJyYXMgY2FtYmlhIHNpZ25pZmljYWRvLiBDYW1iaWFyIHNpZ25pZmljYWRvIHRyYW5zZm9ybWEgZWwgbXVuZG8uCg=='
Write-Encoded 'docs\decisions\DECISION-TEMPLATE.md' 'IyBELVhYWDogVMOtdHVsbwoKLSBFc3RhZG86IFBlbmRpZW50ZQotIEZlY2hhOgotIFJlc3BvbnNhYmxlOiBIw6ljdG9yIFJhbcOtcmV6CgojIyBEZWNpc2nDs24KCiMjIFBvciBxdcOpIGFob3JhCgojIyBPcGNpb25lcwoKIyMjIE9wY2nDs24gQQoKIyMjIE9wY2nDs24gQgoKIyMjIE9wY2nDs24gQwoKIyMgUmVjb21lbmRhY2nDs24KCiMjIENvc3RvCgojIyBSaWVzZ29zCgojIyBJbXBhY3RvCgotIE1vdG9yOgotIEludGVyZmF6OgotIERhdG9zOgotIFBydWViYXM6Ci0gRXhwZXJpZW5jaWE6CgojIyBSZXZlcnNpYmlsaWRhZAoKIyMgUmVzdWx0YWRvCgpQZW5kaWVudGUsIGFwcm9iYWRhIG8gcmVjaGF6YWRhLgo='
Write-Encoded 'docs\art\ASSET_LICENSES.md' 'IyBSZWdpc3RybyBkZSByZWN1cnNvcyB5IGxpY2VuY2lhcwoKTm8gaGF5IHJlY3Vyc29zIGV4dGVybm9zIGFwcm9iYWRvcyB0b2RhdsOtYS4KCkNhZGEgcmVjdXJzbyBmdXR1cm8gZGViZSByZWdpc3RyYXIgaWRlbnRpZmljYWRvciwgcnV0YSwgZnVlbnRlLCByZXNwb25zYWJsZSwgZmVjaGEsIGxpY2VuY2lhIG8gY29uZGljaW9uZXMgZGUgdXNvLCB0cmFuc2Zvcm1hY2lvbmVzIHkgZXN0YWRvIGRlIGFwcm9iYWNpw7NuLgo='
Write-Encoded 'docs\art\PROMPT_LIBRARY.md' 'IyBCaWJsaW90ZWNhIGRlIHByb21wdHMgdmlzdWFsZXMKCk5vIGNvbnRpZW5lIHByb21wdHMgYXByb2JhZG9zIHRvZGF2w61hLgoKTG9zIHByb21wdHMgc2UgYWdyZWdhcsOhbiBkZXNwdcOpcyBkZSBhcHJvYmFyIHVuYSBkaXJlY2Npw7NuIHZpc3VhbCBjb25jcmV0YS4gRGViZW4gZGVzY3JpYmlyIGNvbXBvc2ljacOzbiwgcGFsZXRhLCBwZXJzcGVjdGl2YSB5IGZ1bmNpw7NuLCBzaW4gcGVkaXIgaW1pdGFjacOzbiBkZSBhcnRpc3RhcyB2aXZvcywgbWFyY2FzLCBwZXJzb25hamVzIG8gZXN0aWxvcyBwcm90ZWdpZG9zLgo='
Write-Encoded 'scripts\Project-Context.ps1' 'I3JlcXVpcmVzIC1WZXJzaW9uIDUuMQpbQ21kbGV0QmluZGluZygpXQpwYXJhbShbaW50XSRSZWNlbnRFbnRyaWVzID0gMykKCiRyb290ID0gU3BsaXQtUGF0aCAtUGFyZW50ICRQU1NjcmlwdFJvb3QKV3JpdGUtSG9zdCAnQ29udGV4dG8gbcOtbmltbyBwYXJhIElBJyAtRm9yZWdyb3VuZENvbG9yIEN5YW4KQCgnQ0xBVURFLm1kJywnUFJPSkVDVF9HRU5FU0lTLm1kJywnZG9jc1xTVEFUVVMubWQnLCdkb2NzXDMyX2RlY2lzaW9uX2JhY2tsb2cubWQnLCdkb2NzXDMzX2FpX2hhbmRvZmYubWQnKSB8CiAgRm9yRWFjaC1PYmplY3QgeyBXcml0ZS1Ib3N0ICItICRfIiB9CldyaXRlLUhvc3QgIi0gZG9jc1xiaXRhY29yYS5tZDogJFJlY2VudEVudHJpZXMgZW50cmFkYXMgcmVjaWVudGVzIiAKV3JpdGUtSG9zdCAnRGVzcHXDqXMsIGFkanVudGEgc29sbyBsb3MgYXJjaGl2b3MgcmVsYWNpb25hZG9zIGNvbiBsYSB0YXJlYS4nIC1Gb3JlZ3JvdW5kQ29sb3IgWWVsbG93Cg=='

# Reforzar identidad sin reescribir documentos históricos.
$readme = Join-Path $ProjectPath 'README.md'
if (Test-Path $readme) {
  $text = [IO.File]::ReadAllText($readme, [Text.Encoding]::UTF8)
  if ($text -notmatch 'videojuego 2D de rompecabezas lingüísticos') {
    $identity = "`r`n## Identidad oficial`r`n`r`nZelogiG es un videojuego 2D de rompecabezas lingüísticos donde las palabras reescriben el mundo.`r`n"
    [IO.File]::WriteAllText($readme, $text + $identity, (New-Object Text.UTF8Encoding($false)))
  }
}

# Agregar entrada sin depender del helper.
$logPath = Join-Path $ProjectPath 'docs\bitacora.md'
if (Test-Path $logPath) {
  $content = [IO.File]::ReadAllText($logPath, [Text.Encoding]::UTF8)
  if ($content -notmatch 'Elevación técnica, creativa y operativa') {
    $entry = @"
## $(Get-Date -Format 'yyyy-MM-dd') - Elevación técnica, creativa y operativa

- **Estado:** COMPLETO
- **Que se hizo:** Se definieron arquitectura funcional del motor, aplicación práctica de SOLID, dirección artística, flujo de recursos con IA, entorno local, laboratorio, proceso de niveles, puertas de calidad, decisiones pendientes y protocolo de entrega a otras IA.
- **Decision + porque:** [Seguro] ZelogiG se consolida como videojuego 2D de rompecabezas lingüísticos. El motor seguirá siendo local, determinista y desacoplado; CSS y SVG serán la base visual del MVP; las decisiones estructurales se presentarán al propietario antes de modificar código.
- **Contexto:** Lectura directa de la documentación del proyecto y decisiones del propietario; graphify no disponible y no generado.
- **Validacion:** Archivos generados con PowerShell 5.1. Validaciones de Node.js pendientes por bloqueo corporativo.
- **Costo:** No disponible desde este entorno; no se inventan tokens ni USD.
- **Siguiente paso:** Publicar la documentación, instalar Node.js en un equipo autorizado y ejecutar validación de tipos, pruebas y servidor local.
- **Bloqueos / pendientes de humano:** Node.js no disponible en el equipo corporativo. Autenticación de GitHub debe usar la cuenta propietaria del repositorio.

### Decisiones deliberadas, no deshacer

- ZelogiG es un juego, no un simulador profesional.
- Motor funcional y determinista.
- CSS y SVG para el MVP; IA para conceptos bajo revisión humana.
- Cinco niveles manuales antes de crear un editor.
- Toda decisión estructural se presenta antes de modificar código.

---

"@
    $marker = '---'
    $index = $content.IndexOf($marker)
    if ($index -ge 0) {
      $insertAt = $index + $marker.Length
      $updated = $content.Substring(0,$insertAt) + "`r`n`r`n" + $entry + $content.Substring($insertAt).TrimStart("`r","`n")
      [IO.File]::WriteAllText($logPath, $updated, (New-Object Text.UTF8Encoding($false)))
      Write-Host 'ACTUALIZADO: docs\bitacora.md' -ForegroundColor Green
    }
  }
}

$audit = Join-Path $ProjectPath 'scripts\Audit-ZelogiG.ps1'
if (Test-Path $audit) { & $audit }

if ($Commit -or $Push) {
  Push-Location $ProjectPath
  try {
    git add .
    $pending = git status --porcelain
    if ($pending) { git commit -m 'docs: elevate ZelogiG architecture and production standards' }
    else { Write-Host 'Git: no hay cambios para commit.' -ForegroundColor Yellow }
    if ($Push) { git push -u origin main }
  }
  finally { Pop-Location }
}

Write-Host ''
Write-Host 'Elevación completada.' -ForegroundColor Cyan
Write-Host 'Sin -Commit solo se modifican archivos. Con -Commit se crea commit. Con -Push también intenta publicar.' -ForegroundColor White
